language: python
git:
  submodules: false
python:
  - 2.7
  - 3.4
before_install:
  - git submodule update --init --recursive || true
install:
  - python setup.py install
script: python -c "import pygit2"
