version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-import:
    executor: python/default
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: sudo apt-get install cmake gcc libffi-dev
      - run: python3 -m venv venv
      - run: . venv/bin/activate && pip install . || true
      - run: venv/bin/python -c "import pygit2"

workflows:
  main:
    jobs:
      - build-and-import
